// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamProjectServer.Data;
using TeamProjectServer.Models;

#nullable disable

namespace TeamProjectServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamProjectServer.Models.Accessory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<float>("GoldPer")
                        .HasColumnType("real");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<float>("HPPer")
                        .HasColumnType("real");

                    b.Property<float>("Hp")
                        .HasColumnType("real");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<float>("MPPer")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("accessorys");
                });

            modelBuilder.Entity("TeamProjectServer.Models.Artifact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("artifacts");
                });

            modelBuilder.Entity("TeamProjectServer.Models.PlayerAccountData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float>("ATKPower")
                        .HasColumnType("real");

                    b.Property<float>("ATKSpeed")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamage")
                        .HasColumnType("real");

                    b.Property<float>("CriticalRate")
                        .HasColumnType("real");

                    b.Property<float>("CurGold")
                        .HasColumnType("real");

                    b.Property<float>("EXPMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("GoldMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("HPRegenPerSec")
                        .HasColumnType("real");

                    b.Property<List<InventorySlot>>("Inventory")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<float>("MPRegenPerSec")
                        .HasColumnType("real");

                    b.Property<float>("MaxHP")
                        .HasColumnType("real");

                    b.Property<float>("MaxMP")
                        .HasColumnType("real");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("playerAccountData");
                });

            modelBuilder.Entity("TeamProjectServer.Models.PlayerInit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float>("ATKPower")
                        .HasColumnType("real");

                    b.Property<float>("ATKSpeed")
                        .HasColumnType("real");

                    b.Property<float>("CriticalDamage")
                        .HasColumnType("real");

                    b.Property<float>("CriticalRate")
                        .HasColumnType("real");

                    b.Property<float>("CurGold")
                        .HasColumnType("real");

                    b.Property<float>("EXPMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("GoldMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("HPRegenPerSec")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<float>("MPRegenPerSec")
                        .HasColumnType("real");

                    b.Property<float>("MaxHP")
                        .HasColumnType("real");

                    b.Property<float>("MaxMP")
                        .HasColumnType("real");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("playerInits");
                });

            modelBuilder.Entity("TeamProjectServer.Models.Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Elemnet")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("TeamProjectServer.Models.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("stages");
                });

            modelBuilder.Entity("TeamProjectServer.Models.Weapon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float>("CriticalDMG")
                        .HasColumnType("real");

                    b.Property<float>("CriticalRate")
                        .HasColumnType("real");

                    b.Property<string>("EffectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<float>("EquipATK")
                        .HasColumnType("real");

                    b.Property<float>("GoldPer")
                        .HasColumnType("real");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PassiveATK")
                        .HasColumnType("real");

                    b.Property<string>("SoundKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Weapon");
                });
#pragma warning restore 612, 618
        }
    }
}
